name 'continuent/tungsten'
version '0.1.0'

author 'Continuent'
license 'Apache 2.0'
project_page 'https://github.com/continuent/continuent-tungsten'
source 'https://github.com/continuent/continuent-tungsten'
summary 'Module for installing Continuent Tungsten'
description 'Configure servers for running Continuent Tungsten'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
dependency 'puppetlabs/ntp', '>= 3.0.0'
dependency 'puppetlabs/java', '>= 1.0.1'
dependency 'puppetlabs/firewall', '>= 0.4.0'
dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'continuent/percona_repo', '>= 0.1.0'