#!/bin/bash

WORKGIT=$1
BUILDDIR=$2
mkdir logs > /dev/null

chmod +x get_modules
./get_modules $BUILDDIR $WORKGIT



for t in centos6-cluster u14.04-cluster
do
   rm -rf $t/tungsten
   git clone $WORKGIT $t/tungsten
   docker build  -t="continuent/$t" $t | grep Error:
   $t/launch $BUILDDIR/$basedir
done

#Wait for the containers to start and tungsten to install.
sleep 10m

RC=0
for node in cdb1 udb1
do

   docker-enter $node ps -ef > logs/$node.log
   c=$(cat logs/$node.log|grep tungsten-manager|wc -l)

   if [ $c -eq 0 ]
   then
      echo "Error: Tungsten failed to launch on $node"
      RC=2
   fi
done

if [ $RC == 0 ]
then

  echo "Cleaning up old Containers"

  for type in u c
  do
    for node in db1 db2 db3
    do
      docker stop ${type}${node}  > /dev/null
      docker rm ${type}${node}  > /dev/null
    done
  done
fi


exit $RC
