#!/bin/bash

WORKGIT=$1
BUILDDIR=$2
RPMPREFIX=$3
DEBPREFIX=$4
mkdir logs > /dev/null

chmod +x get_modules
./get_modules $BUILDDIR $WORKGIT  $RPMPREFIX $DEBPREFIX



for t in  centos6-cluster u1404-cluster centos5-cluster
do
   #rm -rf $t/tungsten
   #git clone $WORKGIT $t/tungsten

   docker build  -t="continuent/$t" $t | grep Error:
   chmod +x $t/launch
   $t/launch $BUILDDIR/$basedir
done

#Wait for the containers to start and tungsten to install.
sleep 15m

RC=0
for node in  cdb1 udb1 c5db1
do

   docker-enter $node ps -ef > logs/$node.log
   c=$(cat logs/$node.log|grep tungsten-manager|wc -l)

   if [ $c -eq 0 ]
   then
      echo "Error: Tungsten failed to launch on $node"
      RC=2
   else
      echo "OK: Tungsten cluster launched on $node"
   fi
done

if [ $RC == 0 ]
then

  echo "Cleaning up old Containers"

  for type in u c c5
  do
    for node in db1 db2 db3
    do
      docker stop ${type}${node}  > /dev/null
      docker rm ${type}${node}  > /dev/null
    done
  done
fi


exit $RC
