#!/bin/bash
#

os=$1
BUILDDIR=$2

echo "Operating System =  $os"
rm -rf base$os/tungsten
docker build  -t="cbase/$os" base$os | grep Error:
for f in puppet/*.pp
do
  echo " ... $f"
  basedir=$(dirname $f)
  pwd=$(pwd)
  filename=$(basename $f)
  echo "Starting $os:$filename"
  docker run --rm=true -v $BUILDDIR/$basedir:/mnt cbase/$os puppet apply /mnt/$filename --modulepath=/mnt/modules &> logs/$os.$filename.log
  c=$(cat logs/$os.$filename.log|grep Error|grep -v Unsupported|wc -l)
  if [ $c -ne 0 ]
  then
    RC=2
    touch logs/errors_exist
    cat logs/$os.$filename.log|grep Error|grep -v Unsupported
  #else
  #    cat logs/$os.$filename.log|grep supported
  fi
done
