#!/bin/bash
#

docker images | grep '<none>' | awk '{print $3}'|xargs docker rmi &> /dev/null
WORKGIT=$1
BUILDDIR=$2
mkdir logs > /dev/null

chmod +x get_modules
./get_modules $BUILDDIR $WORKGIT


for os in centos5 centos6 squeeze wheezy ubuntu.10.04 ubuntu.12.04 ubuntu.14.04
do
  echo "Operating System =  $os"
  rm -rf base$os/tungsten
  docker build -t="cbase/$os" base$os | grep Error:
  for f in puppet/*.pp
  do
   echo " ... $f"
   basedir=$(dirname $f)
   pwd=$(pwd)
   filename=$(basename $f)
   docker run --rm=true -v $BUILDDIR/$basedir:/mnt cbase/$os puppet apply /mnt/$filename --modulepath=/mnt/modules &> logs/$os.$filename.log
   cat logs/$os.$filename.log|grep Error|grep -v Unsupported
  done
done
