FROM ubuntu:14.04
MAINTAINER Neil Armitage <narmitage@vmware.com>

RUN apt-get update
RUN apt-get install -y  puppet rsync openjdk-7-jdk
RUN /usr/bin/apt-key adv --keyserver keyserver.ubuntu.com:80 --recv-keys CD2EFD2A
